### ISSUE TITLE
请问可以加个链接吗？

### ISSUE THREAD

**Issue by wangshunping** [Yixiaohan/codeparkshare#5]
最近 在写 requests 源码阅读。

可以把我链接加进去吗？

https://github.com/wangshunping/read_requests

多谢，如果需要 pr 请告知！

**Comment by Yixiaohan** [comment]
当然可以。 @wangshunping

**Comment by Yixiaohan** [comment]
当然可以，来个 pr 吧 :+1:  @wangshunping
