### ISSUE TITLE
所以，请问有python讨论群吗？

### ISSUE THREAD

**Issue by sara15** [Yixiaohan/codeparkshare#7]
所以，请问有python讨论群吗？
求拉。
刚刚开始学python。今年要读Data Science
QQ 2911零零5304 

 **若有打扰，还请包涵。**

**Comment by yc-kata** [comment]
python数据处理 255913825

在 2016-04-02 07:30:46，S <notifications@github.com> 写道：


所以，请问有python讨论群吗？
求拉。
刚刚开始学python。今年要读Data Science
QQ 2911零零5304

若有打扰，还请包涵。

**Comment by Yixiaohan** [comment]
@sara15 有QQ群，但是，聊技术的不多。QQ群不适合聊技术话题。初学者的话，多写代码、多使用Google 搜索即可。
